const quotes = [
  'This is the product of the year, incredible!',
  "I got what I ordered, isn't that amazing?",
  'I am going to Mars and I could not go without this, thank you',
  'I have tried it out, does not impress but does the job',
  'My wife was so happy I got another one!',
];

const usStates = [
  'Alaska',
  'Alabama',
  'Arkansas',
  'American Samoa',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'District of Columbia',
  'Delaware',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Iowa',
  'Idaho',
  'Illinois',
  'Indiana',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Massachusetts',
  'Maryland',
  'Maine',
  'Michigan',
  'Minnesota',
  'Missouri',
  'Mississippi',
  'Montana',
  'North Carolina',
  'North Dakota',
  'Nebraska',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'Nevada',
  'New York',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Virginia',
  'Virgin Islands',
  'Vermont',
  'Washington',
  'Wisconsin',
  'West Virginia',
  'Wyoming',
];

const getQuote = () => {
  return {
    quote: quotes[Math.floor(Math.random() * quotes.length)],
    name: `Stranger ${Math.floor(Math.random() * 1000)}`,
    usState: usStates[Math.floor(Math.random() * usStates.length)],
  };
};

export default getQuote;
